/*
Mindwm API

This document describes the documentation, a collection of JSON schemas and example cloudevent and payloads

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package MindWM

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Neo4jChangeDataCaptureMetaSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Neo4jChangeDataCaptureMetaSource{}

// Neo4jChangeDataCaptureMetaSource struct for Neo4jChangeDataCaptureMetaSource
type Neo4jChangeDataCaptureMetaSource struct {
	Hostname string `json:"hostname"`
}

type _Neo4jChangeDataCaptureMetaSource Neo4jChangeDataCaptureMetaSource

// NewNeo4jChangeDataCaptureMetaSource instantiates a new Neo4jChangeDataCaptureMetaSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNeo4jChangeDataCaptureMetaSource(hostname string) *Neo4jChangeDataCaptureMetaSource {
	this := Neo4jChangeDataCaptureMetaSource{}
	this.Hostname = hostname
	return &this
}

// NewNeo4jChangeDataCaptureMetaSourceWithDefaults instantiates a new Neo4jChangeDataCaptureMetaSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNeo4jChangeDataCaptureMetaSourceWithDefaults() *Neo4jChangeDataCaptureMetaSource {
	this := Neo4jChangeDataCaptureMetaSource{}
	return &this
}

// GetHostname returns the Hostname field value
func (o *Neo4jChangeDataCaptureMetaSource) GetHostname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value
// and a boolean to check if the value has been set.
func (o *Neo4jChangeDataCaptureMetaSource) GetHostnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hostname, true
}

// SetHostname sets field value
func (o *Neo4jChangeDataCaptureMetaSource) SetHostname(v string) {
	o.Hostname = v
}

func (o Neo4jChangeDataCaptureMetaSource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Neo4jChangeDataCaptureMetaSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hostname"] = o.Hostname
	return toSerialize, nil
}

func (o *Neo4jChangeDataCaptureMetaSource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hostname",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNeo4jChangeDataCaptureMetaSource := _Neo4jChangeDataCaptureMetaSource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNeo4jChangeDataCaptureMetaSource)

	if err != nil {
		return err
	}

	*o = Neo4jChangeDataCaptureMetaSource(varNeo4jChangeDataCaptureMetaSource)

	return err
}

type NullableNeo4jChangeDataCaptureMetaSource struct {
	value *Neo4jChangeDataCaptureMetaSource
	isSet bool
}

func (v NullableNeo4jChangeDataCaptureMetaSource) Get() *Neo4jChangeDataCaptureMetaSource {
	return v.value
}

func (v *NullableNeo4jChangeDataCaptureMetaSource) Set(val *Neo4jChangeDataCaptureMetaSource) {
	v.value = val
	v.isSet = true
}

func (v NullableNeo4jChangeDataCaptureMetaSource) IsSet() bool {
	return v.isSet
}

func (v *NullableNeo4jChangeDataCaptureMetaSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNeo4jChangeDataCaptureMetaSource(val *Neo4jChangeDataCaptureMetaSource) *NullableNeo4jChangeDataCaptureMetaSource {
	return &NullableNeo4jChangeDataCaptureMetaSource{value: val, isSet: true}
}

func (v NullableNeo4jChangeDataCaptureMetaSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNeo4jChangeDataCaptureMetaSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


